version: '3.8'

services:
  db:
    image: docker.arvancloud.ir/postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_commerce_data:/var/lib/postgresql
    networks:
      - backend
    restart: always

  redis:
    image: docker.arvancloud.ir/redis:5
    container_name: redis
    networks:
      - backend
    restart: always

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=3"
    volumes:
      - .:/app
      - static_data:/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8002:8000"
    networks:
      - backend
    restart: always

volumes:
  postgres_commerce_data:
  static_data:

networks:
  backend:
